force-app/main/default/objects/Asset/fields/Quote_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quote Line Item</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Cancelled_LineItem__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_LineItem__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled LineItem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/CreatedAsset__c.field-meta.xml
<CustomField>
    <fullName>CreatedAsset__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CreatedAsset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/OLI_Status__c.field-meta.xml
<CustomField>
    <fullName>OLI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Entitlement Processing Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_End_Date__c</fullName>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerCancellationHelper.cls
public class QuoteTriggerCancellationHelper {
  public static void handleCancellation(List<QuoteLineItem> qlis, Quote q) {
    List<Asset> assetsToBeCreated = new List<Asset>();
    List<Asset> assetsToBeDeleted = new List<Asset>();
    List<QuoteLineItem> qlisToBeUpdated = new List<QuoteLineItem>();
    for (QuoteLineItem qli : qlis) {
      if (
        qli.cancelled_lineitem__c &&
        qli.Asset__c != null &&
        qli.Service_End_Date__c != null
      ) {
        if (qli.CreatedAsset__c == false) {
          Asset newAsset = new Asset();
          //Delete existing asset
          assetsToBeDeleted.add(new Asset(Id = qli.Asset__c));
          newAsset.Product2Id = qli.Product2Id;
          newAsset.Quote_Line_Item__c = qli.Id;
          newAsset.AccountId = q.AccountId;
          newAsset.Status = 'Cancelled';
          newAsset.Quantity = qli.Quantity;
          newAsset.Price = qli.UnitPrice * (qli.Quantity);
          newAsset.Name = 'ASS-' + qli.Id.toString();
          newAsset.Service_End_Date__c = qli.Service_End_Date__c;
          assetsToBeCreated.add(newAsset);

          qlisToBeUpdated.add(
            new QuoteLineItem(
              Id = qli.Id,
              CreatedAsset__c = true,
              OLI_Status__c = 'Complete'
            )
          );
        }
      } else {
        if (qli.createdasset__c == false) {
          if (qli.Asset__c == null) {
            qli.OLI_Status__c = 'Entitlement Processing Error';
            qli.Error_Description__c = 'Asset is not linked to the quote line item';
            qlisToBeUpdated.add(qli);
            continue;
          }
          if (qli.Service_End_Date__c == null) {
            qli.OLI_Status__c = 'Entitlement Processing Error';
            qli.Error_Description__c = 'Service end date is not set';
            qlisToBeUpdated.add(qli);
            continue;
          }
        }
      }
    }
    try {
      if (!assetsToBeDeleted.isEmpty()) {
        delete assetsToBeDeleted;
      }
      if (!assetsToBeCreated.isEmpty()) {
        insert assetsToBeCreated;
      }
      if (!qlisToBeUpdated.isEmpty()) {
        update qlisToBeUpdated;
      }
    } catch (Exception e) {
      System.debug('Error processing cancellation: ' + e.getMessage());
      throw new QuoteTriggerCancellationHelper.QuoteTriggerCancellationException(
        e.getMessage()
      );
    }
  }
  public class QuoteTriggerCancellationException extends Exception {
  }
}